extends TestCase
## The stage-PROXY visual chain of [code]docs/EXTENSION_PIPELINE.md[/code] §2.1
## and §9, and Architectural Invariant I-1 asserted from the presentation side.
##
## Until this session [code]VisualRoot[/code] was created empty and nothing in
## the project ever put a mesh in the world, so [method
## AssemblyRuntime.visual_decoupling_violations] had nothing to walk and passed
## vacuously. It is a real assertion now, and this file is what makes it one.
##
## The interesting property is the one §2.1 calls visual honesty: every shipped
## part leaves [member PartVisualProfile.proxy_primitives] empty, so its greybox
## is generated by mirroring its [ColliderProfile] and the mesh a player sees is
## the shape a round hits. That is asserted here by extent rather than assumed,
## because it is the guarantee that makes a greybox build worth aiming at — and
## the first STAGE_FINAL part to ship will break it deliberately, under §7's
## measured divergence bound.

const CORE_KEY := &"core.command.compact.t2"
const PANEL_KEY := &"str.panel.medium.t2"
const WHEEL_KEY := &"mot.wheeled.allroad.t2"

const CORE_ORIGIN := Vector3i(24, 4, 24)
const DECK_ORIGIN := Vector3i(24, 7, 24)

## Both parts here carry one authored primitive, so a mirrored proxy is one
## primitive too and the extent comparison below is exact rather than a union.
const CORE_PRIMITIVES := 1

var _core: PartDefinition = null
var _panel: PartDefinition = null
var _contexts: Array[BuildContext] = []
var _runtimes: Array[AssemblyRuntime] = []


func before_all() -> void:
	_core = PartRegistry.definition_by_key(CORE_KEY)
	_panel = PartRegistry.definition_by_key(PANEL_KEY)


func after_all() -> void:
	for runtime in _runtimes:
		runtime.free()
	_runtimes.clear()
	for ctx in _contexts:
		ctx.dispose()
	_contexts.clear()


## ===== §9 SPAWN ========================================================


func test_every_committed_part_gets_a_mesh_under_the_visual_root() -> void:
	var runtime := _adopted_runtime()
	check_eq(runtime.visual_root.get_child_count(), 2, "one MeshInstance3D per committed part")
	for slot: int in [0, 1] as Array[int]:
		var node := runtime.visual_of(slot)
		check_not_null(node, "slot %d has a visual" % slot)
		if node != null:
			check_not_null(node.mesh, "slot %d's visual carries a mesh" % slot)


func test_the_visual_records_its_own_path_on_the_instance_state() -> void:
	# Doc 08 §9's repair and damage-state swap both find the node this way, and a
	# path that is never written reads as a part with no visual to swap.
	var runtime := _adopted_runtime()
	var st := runtime.state(0)
	check_ne(st.visual_node_path, NodePath(), "slot 0 recorded its visual path")
	check_eq(
		runtime.visual_root.get_node_or_null(st.visual_node_path),
		runtime.visual_of(0),
		"and the path resolves to the node the runtime holds"
	)


func test_meshes_are_on_the_assembly_visual_render_layer() -> void:
	# CLAUDE.md §5.2. A mesh on the default layer is drawn by the icon
	# SubViewport and by the garage camera as well as by the match camera, which
	# presents as a part appearing in a catalogue thumbnail of a different part.
	var runtime := _adopted_runtime()
	var node := runtime.visual_of(0)
	check_eq(
		node.layers, RenderLayers.LAYER_ASSEMBLY_VISUAL,
		"the part mesh occupies the Assembly visual layer alone"
	)
	check_true(
		(RenderLayers.CULL_MATCH_CAMERA & RenderLayers.LAYER_ASSEMBLY_VISUAL) != 0,
		"and the match camera renders that layer"
	)


## ===== INVARIANT I-1 ===================================================


func test_a_populated_visual_root_still_carries_no_collision() -> void:
	var runtime := _adopted_runtime()
	# The assertion that was vacuous until meshes existed.
	check_true(runtime.visual_root.get_child_count() > 0, "the walk has something to walk")
	check_eq(
		runtime.visual_decoupling_violations().size(), 0,
		"no CollisionObject3D or CollisionShape3D under a populated VisualRoot"
	)
	for node: Node in runtime.visual_root.get_children():
		check_false(node is CollisionObject3D, "%s is not a collision object" % node.name)


func test_the_mirrored_proxy_has_the_collider_extent() -> void:
	# §2.1's visual honesty, by value. A proxy generated from the collider must
	# be the collider's size: if it is not, a greybox build is showing the player
	# a silhouette they cannot hit, and every aiming decision made against it is
	# made against a lie.
	check_eq(
		_core.visual_profile.proxy_primitives.size(), 0,
		"the Core Module authors no proxy primitives, so the collider is mirrored"
	)
	check_eq(_core.collider_profile.primitives.size(), CORE_PRIMITIVES, "one authored primitive")

	var prim: ColliderPrimitiveDef = _core.collider_profile.primitives[0]
	check_eq(
		prim.kind, ColliderPrimitiveDef.PrimitiveKind.BOX,
		"and it is a box, which the extent comparison below assumes"
	)
	var mesh := ProxyMeshCache.get_or_build(_core)
	check_not_null(mesh, "the mirrored proxy built")
	var aabb := mesh.get_aabb()
	var expected := prim.half_extents_m * 2.0
	check_approx(aabb.size.x, expected.x, "proxy width matches the collider", 1e-3)
	check_approx(aabb.size.y, expected.y, "proxy height matches the collider", 1e-3)
	check_approx(aabb.size.z, expected.z, "proxy depth matches the collider", 1e-3)


## ===== §2.1 CACHE ======================================================


func test_two_instances_of_one_part_share_one_mesh() -> void:
	# Forty panels on one Assembly are one ArrayMesh. Without this every panel
	# triangulates its own copy at spawn, which presents as a spawn hitch rather
	# than as anything a profiler points at directly.
	var first := ProxyMeshCache.get_or_build(_panel)
	var second := ProxyMeshCache.get_or_build(_panel)
	check_true(first == second, "the cache returns the same resource twice")

	var runtime := _adopted_runtime()
	check_true(
		runtime.visual_of(1).mesh == first,
		"and a spawned part uses the cached resource rather than a copy of it"
	)


func test_the_cache_survives_being_asked_for_an_unbuildable_part() -> void:
	# A null is cached deliberately: a part with no buildable proxy will not
	# acquire one by being asked twice, and re-running the builder per spawn
	# would re-emit the same warning for the life of the match.
	var before := ProxyMeshCache.size()
	check_null(ProxyMeshCache.get_or_build(null), "a null definition builds nothing")
	check_eq(ProxyMeshCache.size(), before, "and is not cached under a key")


## ===== §2.1 CLASS TINT =================================================


func test_each_part_class_gets_a_distinct_greybox_tint() -> void:
	# doc 13 §2.1's table exists for legibility: an Assembly in one grey is a
	# silhouette with no parts in it, and a player cannot see where the Prime
	# Mover they are meant to be protecting sits.
	var seen: Array[Color] = []
	for c: int in PartEnums.PartClass.size():
		var mat := GreyboxMaterial.for_class(c as PartEnums.PartClass, Color.WHITE)
		check_not_null(mat, "class %d has a material" % c)
		for other: Color in seen:
			check_false(
				mat.albedo_color.is_equal_approx(other),
				"class %d's tint is distinct from every earlier one" % c
			)
		seen.append(mat.albedo_color)


func test_the_shared_material_is_shared() -> void:
	var a := GreyboxMaterial.for_class(PartEnums.PartClass.STRUCTURAL_COMPONENT, Color.WHITE)
	var b := GreyboxMaterial.for_class(PartEnums.PartClass.STRUCTURAL_COMPONENT, Color.WHITE)
	check_true(a == b, "one material per class and tint, not one per instance")


## ===== SIMULATION FOLLOWING ============================================


func test_releasing_a_part_hides_its_mesh_and_restoring_shows_it() -> void:
	# The one place presentation is obliged to follow the simulation rather than
	# merely permitted to. A shipped part's greybox is its collider exactly, so a
	# mesh left behind by a disabled shape is geometry the player can see and
	# cannot hit — which reads as a round passing through armour.
	var runtime := _adopted_runtime()
	var node := runtime.visual_of(1)
	check_true(node.visible, "the panel starts visible")

	runtime.release_part(1)
	check_false(node.visible, "release_part hides it with its shapes")

	runtime.restore_part(1)
	check_true(node.visible, "and doc 08 §11's repair path brings it back")


func test_a_severed_island_takes_its_mesh_with_it() -> void:
	var runtime := _adopted_runtime()
	var debris := DebrisBodyRef.new()
	EventBus.get_tree().root.add_child(debris)
	runtime.detach_colliders_to(debris, 1, Vector3.ZERO)
	check_false(
		runtime.visual_of(1).visible,
		"the island's shapes are on the debris body, so its mesh leaves this hull"
	)
	debris.free()


## ===== DOC 12 §9.2 =====================================================


func test_the_part_visual_tag_suppresses_every_mesh() -> void:
	# A dedicated server builds no ArrayMesh at all. Nothing simulated reads a
	# mesh — Invariant I-1 stated as a capability rather than as a prohibition —
	# so this must not change a single collider.
	SubsystemGate.disable([AssemblyRuntime.TAG_PART_VISUAL])
	var runtime := _new_runtime()
	runtime.adopt(_context_with_core_and_panel())
	SubsystemGate.enable([AssemblyRuntime.TAG_PART_VISUAL])

	check_eq(runtime.visual_root.get_child_count(), 0, "no meshes were built")
	check_null(runtime.visual_of(0), "and no visual is recorded")
	check_true(runtime.shape_count() > 0, "while the collision geometry is untouched")


## ===== FIXTURE =========================================================


func _new_runtime() -> AssemblyRuntime:
	var runtime := AssemblyRuntime.new()
	_runtimes.append(runtime)
	EventBus.get_tree().root.add_child(runtime)
	return runtime


func _adopted_runtime() -> AssemblyRuntime:
	var runtime := _new_runtime()
	runtime.adopt(_context_with_core_and_panel())
	return runtime


func _context_with_core_and_panel() -> BuildContext:
	var ctx := BuildContext.with_physics(11)
	_contexts.append(ctx)
	PlacementValidator.commit(ctx, PlacementCandidate.create(_core, CORE_ORIGIN, 0))
	PlacementValidator.commit(ctx, PlacementCandidate.create(_panel, DECK_ORIGIN, 0))
	return ctx
