class_name OrientationTable
extends RefCounted
## The frozen 24-element orientation group of
## [code]docs/GRID_SNAPPING_LOGIC.md[/code] §4.
##
## An Assembly part may take any of the 24 rotations of the proper octahedral
## group. Mirroring is excluded: mirrored parts would need mirrored collider
## primitives and mirrored attachment polarities, doubling the validation
## surface for no gameplay benefit.
##
## [b]The index-to-basis mapping is frozen[/b] — it is serialised in blueprints
## and network packets. It is generated by construction rather than stored as a
## literal table so that the ordering is reproducible and auditable, and the
## construction below must not be altered.
##
## Index decomposes as [code]orientation_index = up_facing * 4 + roll_quarter[/code].

const COUNT: int = SyndicateConstants.ORIENTATION_COUNT

## Which part-local axis becomes world +Y, in fixed order.
## [b]Order is normative and MUST NOT change.[/b]
const UP_AXES: Array[Vector3i] = [
	Vector3i(0, 1, 0),  # 0: identity up
	Vector3i(0, -1, 0),  # 1: inverted
	Vector3i(1, 0, 0),  # 2: rolled right
	Vector3i(-1, 0, 0),  # 3: rolled left
	Vector3i(0, 0, 1),  # 4: pitched back
	Vector3i(0, 0, -1),  # 5: pitched forward
]

## Probe with three distinct absolute components. No two distinct elements of
## the octahedral group map it to the same result, which makes index recovery an
## exact identification rather than an approximation.
const PROBE: Vector3i = Vector3i(1, 2, 3)

const IDENTITY_INDEX: int = 0

static var _bases: Array[Basis] = []
## Row-major 3x3 integer matrices, nine entries per orientation. Kept as a
## packed integer array so that [method rotate_cell] never touches a float.
static var _matrices: PackedInt32Array = PackedInt32Array()
static var _inverse_index: PackedInt32Array = PackedInt32Array()
## Maps a packed probe image back to the orientation index that produced it.
static var _probe_lookup: Dictionary = {}


static func _static_init() -> void:
	_bases.resize(COUNT)
	_matrices.resize(COUNT * 9)
	for up_facing in 6:
		var align := _basis_aligning_y_to(UP_AXES[up_facing])
		for roll in 4:
			var spin := Basis(Vector3(0, 1, 0), float(roll) * PI * 0.5)
			var b := _snap_basis_to_integers((spin * align).orthonormalized())
			var index := up_facing * 4 + roll
			_bases[index] = b
			_write_matrix(index, b)
	_build_probe_lookup()
	_build_inverse_table()


## Shortest rotation carrying part-local +Y onto the requested axis.
static func _basis_aligning_y_to(axis: Vector3i) -> Basis:
	var a := Vector3(axis)
	if a.is_equal_approx(Vector3(0, 1, 0)):
		return Basis()
	if a.is_equal_approx(Vector3(0, -1, 0)):
		return Basis(Vector3(1, 0, 0), PI)
	var rot_axis := Vector3(0, 1, 0).cross(a).normalized()
	return Basis(rot_axis, PI * 0.5)


## Rounds every element to the nearest integer, eliminating trig residue.
##
## [member Basis.x], [code]y[/code] and [code]z[/code] are the basis columns.
## Godot 4.7 removed [code]get_column[/code] and [code]set_column[/code], so the
## columns are read and reassembled directly.
static func _snap_basis_to_integers(b: Basis) -> Basis:
	return Basis(_round_vector(b.x), _round_vector(b.y), _round_vector(b.z))


static func _round_vector(v: Vector3) -> Vector3:
	return Vector3(roundf(v.x), roundf(v.y), roundf(v.z))


## Stores the basis row-major, transposing from the column-major [Basis].
static func _write_matrix(index: int, b: Basis) -> void:
	var base := index * 9
	var cols := [b.x, b.y, b.z]
	for row in 3:
		for col in 3:
			var v: Vector3 = cols[col]
			_matrices[base + row * 3 + col] = int(v[row])


static func _build_probe_lookup() -> void:
	_probe_lookup.clear()
	for i in COUNT:
		_probe_lookup[rotate_cell(i, PROBE)] = i


static func _build_inverse_table() -> void:
	_inverse_index.resize(COUNT)
	for i in COUNT:
		for j in COUNT:
			if compose(i, j) == IDENTITY_INDEX:
				_inverse_index[i] = j
				break


static func basis_for(index: int) -> Basis:
	assert(index >= 0 and index < COUNT, "orientation index out of range: %d" % index)
	return _bases[index]


## Integer rotation of a cell offset. No floating point involved.
static func rotate_cell(index: int, c: Vector3i) -> Vector3i:
	var b := index * 9
	return Vector3i(
		_matrices[b + 0] * c.x + _matrices[b + 1] * c.y + _matrices[b + 2] * c.z,
		_matrices[b + 3] * c.x + _matrices[b + 4] * c.y + _matrices[b + 5] * c.z,
		_matrices[b + 6] * c.x + _matrices[b + 7] * c.y + _matrices[b + 8] * c.z
	)


## An attachment node's face normal rotates with the part. Because the face is
## always an axis unit vector and the basis is integral, the result is always an
## axis unit vector; no normalisation is required.
static func rotate_face(index: int, face: Vector3i) -> Vector3i:
	return rotate_cell(index, face)


## Index of the rotation equal to applying [param b] and then [param a].
static func compose(a: int, b: int) -> int:
	return _probe_lookup[rotate_cell(a, rotate_cell(b, PROBE))]


static func inverse_of(index: int) -> int:
	return _inverse_index[index]


## The upright member of the group whose local [constant Vector3.FORWARD] points
## along [param face], or [constant IDENTITY_INDEX] when [param face] is not an
## axis the group can reach while staying upright.
##
## "Upright" is the second condition and it is what makes the answer unique:
## four of the twenty-four rotations carry forward onto any given horizontal
## axis, and they differ by roll. A Motive Assembly placed with one of the other
## three is a contact rolled onto its side, which is legal in the lattice and
## wrong on the road.
##
## Lives here rather than in a caller because it is a property of the orientation
## group, and it had two would-be owners: the arena fixture wrote it in session
## 14 and the match scene needed the same answer.
static func upright_facing(face: Vector3) -> int:
	for i: int in COUNT:
		var b := basis_for(i)
		if not (b * Vector3.FORWARD).is_equal_approx(face):
			continue
		if (b * Vector3.UP).is_equal_approx(Vector3.UP):
			return i
	return IDENTITY_INDEX


## The first member of the group carrying [param local_axis] onto [param onto],
## or [constant IDENTITY_INDEX] when none does.
##
## Unlike [method upright_facing] the answer is [b]not[/b] unique: four rotations
## carry any axis onto any other and they differ by roll about it. So this is for
## parts whose roll about the carried axis does not read — an Appendage's
## shoulder, whose section is square and whose held Effector Module carries its
## own frame — and [method upright_facing] remains the one to reach for when the
## roll is the difference between a contact on the road and a contact on its side.
##
## It lives here for the reason [method upright_facing] does: which of the
## twenty-four does this is a property of the group, and it had two would-be
## owners the moment a second fixture needed to hang an arm off a hull.
static func first_carrying(local_axis: Vector3, onto: Vector3) -> int:
	for i: int in COUNT:
		if (basis_for(i) * local_axis).is_equal_approx(onto):
			return i
	return IDENTITY_INDEX


## The member of the group that best stands in for [param index] reflected in the
## Assembly's x plane, per [code]docs/GRID_SNAPPING_LOGIC.md[/code] §10.
##
## [b]A reflection is not a rotation and there is no exact answer.[/b] The
## twenty-four are the rotation group; reflecting one produces an improper
## transform with determinant −1, which is not in it. So the reflected frame is
## scored against every member on the two axes that decide how a part reads —
## where it points and which way is up — and the best is returned. For a part
## placed upright and facing an axis, which is every placement a player makes
## with one rotation key, the best is exact: mirroring a contact whose drive face
## points inboard gives the contact whose drive face points inboard on the other
## flank.
##
## Where it is [i]not[/i] exact, the mirrored part is a legal placement that is
## not a perfect reflection, and §10 already says what happens next: it goes
## through the validator like any other placement and is skipped if refused.
static func mirror_x_index(index: int) -> int:
	var b := basis_for(index)
	# Reflect each axis vector in x: the component along x flips, the rest stay.
	var want_forward := Vector3(-b.z.x, b.z.y, b.z.z)
	var want_up := Vector3(-b.y.x, b.y.y, b.y.z)
	var best := index
	var best_score := -INF
	for k: int in COUNT:
		var kb := basis_for(k)
		var score := kb.z.dot(want_forward) + kb.y.dot(want_up)
		if score > best_score:
			best_score = score
			best = k
	return best


## Recovers the orientation index of an integral basis, or -1 when the basis is
## not a member of the group. Used by blueprint import and by the tools that
## bake authored transforms down to an index.
static func index_of_basis(b: Basis) -> int:
	var snapped := _snap_basis_to_integers(b)
	var image := Vector3i(snapped * Vector3(PROBE))
	return _probe_lookup.get(image, -1)
