extends TestCase
## Keeps the section index at the top of each of the thirteen documents true.
##
## A document here runs to two thousand lines and a hundred headings, and the
## question a session asks first is whether a document has anything to say about a
## topic at all — which is a question about its chapters. Each one carries a list
## of its own top-level sections between two markers, generated by
## [code]tools/ci/doc_index.py[/code].
##
## [b]It is checked rather than trusted, and that is `LEARNED_FACTS.md` fact 64.[/b]
## A list that must be maintained by hand to stay honest does not stay honest, and
## it rots in the direction of looking complete — a section added at the end is
## exactly the one a stale index omits, and nothing about the document looks wrong.
## When this fails, the fix is one command:
##
## [codeblock]
## python3 tools/ci/doc_index.py
## [/codeblock]
##
## The rule the generator implements, restated here so this test does not simply
## re-run it: a top-level section is a line matching `## <number>. <title>` outside
## a fenced code block. The number is required, because these documents quote
## GDScript and a `##` doc comment inside a fence is not a heading.

const DOCS_ROOT: String = "res://docs"
const BEGIN: String = "<!-- SECTION INDEX -->"
const END: String = "<!-- END SECTION INDEX -->"
const FENCE: String = "```"

## CLAUDE.md §1. Stated by value rather than counted, so a document deleted or
## added shows up here as well as in the ownership table.
const EXPECTED_DOCUMENT_COUNT: int = 13


func test_every_document_carries_a_section_index() -> void:
	var paths := _documents()
	check_eq(
		paths.size(),
		EXPECTED_DOCUMENT_COUNT,
		"CLAUDE.md §1 names thirteen documents and /docs/ holds %d" % paths.size()
	)
	for path: String in paths:
		var text := SourceScanner.read(path)
		check_true(
			text.contains(BEGIN) and text.contains(END),
			(
				"%s has no section index; run python3 tools/ci/doc_index.py"
				% SourceScanner.short(path)
			)
		)


func test_every_index_names_exactly_the_sections_the_document_has() -> void:
	for path: String in _documents():
		var text := SourceScanner.read(path)
		if not (text.contains(BEGIN) and text.contains(END)):
			continue
		var index := text.substr(
			text.find(BEGIN), text.find(END) + END.length() - text.find(BEGIN)
		)
		var headings := _sections(text)
		var listed := _listed(index)
		check_false(
			headings.is_empty(),
			"%s has no numbered top-level sections" % SourceScanner.short(path)
		)
		# The count first, and separately, because a mismatched length makes every
		# positional comparison below it wrong in the same uninformative way.
		if not check_eq(
			listed.size(),
			headings.size(),
			(
				"%s's index lists %d sections and the document has %d; run "
				+ "python3 tools/ci/doc_index.py"
			) % [SourceScanner.short(path), listed.size(), headings.size()]
		):
			continue
		# Positionally, so a renamed section is caught as well as a missing one —
		# a containment test passes an index that still names the old title for as
		# long as the new one is in there somewhere too.
		for i: int in headings.size():
			check_eq(
				listed[i],
				headings[i],
				(
					"%s's index entry %d disagrees with the heading; run "
					+ "python3 tools/ci/doc_index.py"
				) % [SourceScanner.short(path), i + 1]
			)


## The index must sit above the body, or it is not a way in.
func test_the_index_is_the_first_thing_after_the_title() -> void:
	for path: String in _documents():
		var text := SourceScanner.read(path)
		var begin := text.find(BEGIN)
		if begin < 0:
			continue
		var title := text.find("# ")
		check_true(
			title >= 0 and begin > title and begin - title < 120,
			(
				"%s's index is %d characters after its title rather than directly "
				+ "under it"
			) % [SourceScanner.short(path), begin - title]
		)


## ===== PARSING =========================================================


## `## <number>. <title>` lines outside a fenced block, as "<number>. <title>".
##
## The fence tracking is not decoration: every one of these documents quotes
## GDScript, and a `## Doc comment` inside a fence is indistinguishable from a
## heading to a line-wise match.
static func _sections(text: String) -> PackedStringArray:
	var out := PackedStringArray()
	var fenced := false
	for line: String in text.split("\n"):
		if line.begins_with(FENCE):
			fenced = not fenced
			continue
		if fenced or not line.begins_with("## "):
			continue
		var rest := line.substr(3).strip_edges()
		var dot := rest.find(". ")
		if dot <= 0 or not rest.substr(0, dot).is_valid_int():
			continue
		out.append(rest)
	return out


## The entries an index block names, as "<number>. <title>".
##
## Parsed back out of the rendered row rather than compared as one string, so the
## failure names the section that is wrong instead of printing two paragraphs.
##
## [b]The row is isolated first, and the first version of this did not do that.[/b]
## Splitting the whole block on the separator makes the first segment the markers
## and the preamble with the first entry glued to the end of it, and the preamble
## contains a ". " of its own — so entry one parsed as prose and was dropped, and
## every document reported one section short.
static func _listed(index: String) -> PackedStringArray:
	var out := PackedStringArray()
	for entry: String in _row(index).split("·"):
		var cleaned := entry.replace("**", "").strip_edges()
		var dot := cleaned.find(". ")
		if dot <= 0 or not cleaned.substr(0, dot).is_valid_int():
			continue
		out.append(cleaned)
	return out


## The rendered entry row of an index block: the last non-empty line before the
## closing marker. The generator writes the markers, the preamble, then the row.
static func _row(index: String) -> String:
	var lines := index.split("\n")
	for i: int in range(lines.size() - 1, -1, -1):
		var line := lines[i].strip_edges()
		if line.is_empty() or line == END:
			continue
		return line
	return ""


func _documents() -> PackedStringArray:
	var out := PackedStringArray()
	for name: String in DirAccess.get_files_at(DOCS_ROOT):
		if name.ends_with(".md"):
			out.append("%s/%s" % [DOCS_ROOT, name])
	out.sort()
	return out
