extends TestCase
## Keeps the section index at the top of each of the thirteen documents true.
##
## A document here runs to two thousand lines and a hundred headings, and the
## question a session asks first is whether a document has anything to say about a
## topic at all — which is a question about its chapters. Each one carries a list
## of its own top-level sections between two markers, generated by
## [code]tools/ci/doc_index.py[/code].
##
## [b]It is checked rather than trusted, and that is `LEARNED_FACTS.md` fact 64.[/b]
## A list that must be maintained by hand to stay honest does not stay honest, and
## it rots in the direction of looking complete — a section added at the end is
## exactly the one a stale index omits, and nothing about the document looks wrong.
## When this fails, the fix is one command:
##
## [codeblock]
## python3 tools/ci/doc_index.py
## [/codeblock]
##
## The rule the generator implements, restated here so this test does not simply
## re-run it: a top-level section is a line matching `## <number>. <title>` outside
## a fenced code block. The number is required, because these documents quote
## GDScript and a `##` doc comment inside a fence is not a heading.

const DOCS_ROOT: String = "res://docs"
const BEGIN: String = "<!-- SECTION INDEX -->"
const END: String = "<!-- END SECTION INDEX -->"
const FENCE: String = "```"

## CLAUDE.md §1. Stated by value rather than counted, so a document deleted or
## added shows up here as well as in the ownership table.
const EXPECTED_DOCUMENT_COUNT: int = 13


func test_every_document_carries_a_section_index() -> void:
	var paths := _documents()
	check_eq(
		paths.size(),
		EXPECTED_DOCUMENT_COUNT,
		"CLAUDE.md §1 names thirteen documents and /docs/ holds %d" % paths.size()
	)
	for path: String in paths:
		var text := SourceScanner.read(path)
		check_true(
			text.contains(BEGIN) and text.contains(END),
			(
				"%s has no section index; run python3 tools/ci/doc_index.py"
				% SourceScanner.short(path)
			)
		)


func test_every_index_names_exactly_the_sections_the_document_has() -> void:
	for path: String in _documents():
		var text := SourceScanner.read(path)
		if not (text.contains(BEGIN) and text.contains(END)):
			continue
		var index := text.substr(
			text.find(BEGIN), text.find(END) + END.length() - text.find(BEGIN)
		)
		var headings := _sections(text)
		var listed := _listed(index)
		check_false(
			headings.is_empty(),
			"%s has no numbered top-level sections" % SourceScanner.short(path)
		)
		# The count first, and separately, because a mismatched length makes every
		# positional comparison below it wrong in the same uninformative way.
		if not check_eq(
			listed.size(),
			headings.size(),
			(
				"%s's index lists %d sections and the document has %d; run "
				+ "python3 tools/ci/doc_index.py"
			) % [SourceScanner.short(path), listed.size(), headings.size()]
		):
			continue
		# Positionally, so a renamed section is caught as well as a missing one —
		# a containment test passes an index that still names the old title for as
		# long as the new one is in there somewhere too.
		for i: int in headings.size():
			check_eq(
				listed[i],
				headings[i],
				(
					"%s's index entry %d disagrees with the heading; run "
					+ "python3 tools/ci/doc_index.py"
				) % [SourceScanner.short(path), i + 1]
			)


## The index must sit above the body, or it is not a way in.
func test_the_index_is_the_first_thing_after_the_title() -> void:
	for path: String in _documents():
		var text := SourceScanner.read(path)
		var begin := text.find(BEGIN)
		if begin < 0:
			continue
		var title := text.find("# ")
		check_true(
			title >= 0 and begin > title and begin - title < 120,
			(
				"%s's index is %d characters after its title rather than directly "
				+ "under it"
			) % [SourceScanner.short(path), begin - title]
		)


## ===== IMPLEMENTATION STATUS ===========================================


## Every document carries a status banner, and the banner is checked against the
## source tree rather than trusted.
##
## [b]A document is normative whether or not anything implements it, and the prose
## cannot be told apart.[/b] Four of the thirteen describe software that does not
## exist — `src/net/` holds one file against doc 12's authority matrix, and three
## directories are empty against docs 03, 06 and 10 — while doc 09, which reads
## identically, is fully built and heavily used. A reader deciding whether a figure
## is a measurement or an intention has no way to tell.
##
## The witness is what stops the banner rotting: a path that must exist for a
## `BUILT` or `PARTIAL` claim and must [b]not[/b] exist for a `PLANNED` one, so
## the day somebody writes `src/net/net_server.gd` this test fails and the banner
## has to be updated with it.
const STATUS_WITNESSES: Dictionary = {
	"PART_DATA_SCHEMA.md": ["BUILT", "res://src/autoload/part_registry.gd"],
	"GRID_SNAPPING_LOGIC.md": ["BUILT", "res://src/assembly/lattice/placement_validator.gd"],
	"PART_FUSION_SHADER.md": ["PLANNED", "res://src/vfx/fusion/occupancy_sdf_baker.gd"],
	"DEPENDENCY_TREE_GRAPH.md": ["BUILT", "res://src/assembly/graph/chassis_graph.gd"],
	"DYNAMIC_MASS_PHYSICS.md": ["PARTIAL", "res://src/motion/motive_system.gd"],
	"AUTO_ASSEMBLE_ALGORITHM.md": ["PLANNED", "res://src/assembly/autobuild/auto_assembler.gd"],
	"WEAPON_TARGETING_LOGIC.md": ["PARTIAL", "res://src/combat/effectors/effector_system.gd"],
	"COMPONENT_HEALTH_DAMAGE.md": ["PARTIAL", "res://src/combat/damage/damage_resolver.gd"],
	"TERRAIN_CRATER_DEFORMER.md": ["BUILT", "res://src/world/ground/ground_deform_system.gd"],
	"PROCEDURAL_STRUCTURE_SLICING.md": ["PLANNED", "res://src/world/volumes/convex_slicer.gd"],
	"RESPONSIVE_GARAGE_UI.md": ["PARTIAL", "res://src/ui/garage/garage_screen.gd"],
	"HEADLESS_NETWORK_SYNC.md": ["PLANNED", "res://src/net/net_server.gd"],
	"EXTENSION_PIPELINE.md": ["PARTIAL", "res://src/core/util/proxy_mesh_builder.gd"],
}


func test_every_document_declares_an_implementation_status() -> void:
	for path: String in _documents():
		var name := path.get_file()
		if not check_true(
			STATUS_WITNESSES.has(name), "%s has no declared status" % name
		):
			continue
		var declared: String = STATUS_WITNESSES[name][0]
		var text := SourceScanner.read(path)
		check_true(
			text.contains("**Status: %s" % declared),
			(
				"%s's banner must read '%s'; run python3 tools/ci/doc_index.py"
				% [name, declared]
			)
		)


func test_a_planned_document_has_no_implementation_and_a_built_one_does() -> void:
	for name: String in STATUS_WITNESSES:
		var declared: String = STATUS_WITNESSES[name][0]
		var witness: String = STATUS_WITNESSES[name][1]
		var exists := ResourceLoader.exists(witness) or FileAccess.file_exists(witness)
		if declared == "PLANNED":
			check_false(
				exists,
				(
					"%s is banner-marked PLANNED and %s now exists — the document "
					+ "has an implementation and the banner is lying"
				) % [name, witness]
			)
		else:
			check_true(
				exists,
				(
					"%s is banner-marked %s and its witness %s is missing"
					% [name, declared, witness]
				)
			)


## ===== PARSING =========================================================


## `## <number>. <title>` lines outside a fenced block, as "<number>. <title>".
##
## The fence tracking is not decoration: every one of these documents quotes
## GDScript, and a `## Doc comment` inside a fence is indistinguishable from a
## heading to a line-wise match.
static func _sections(text: String) -> PackedStringArray:
	var out := PackedStringArray()
	var fenced := false
	for line: String in text.split("\n"):
		if line.begins_with(FENCE):
			fenced = not fenced
			continue
		if fenced or not line.begins_with("## "):
			continue
		var rest := line.substr(3).strip_edges()
		var dot := rest.find(". ")
		if dot <= 0 or not rest.substr(0, dot).is_valid_int():
			continue
		out.append(rest)
	return out


## The entries an index block names, as "<number>. <title>".
##
## Parsed back out of the rendered row rather than compared as one string, so the
## failure names the section that is wrong instead of printing two paragraphs.
##
## [b]The row is isolated first, and the first version of this did not do that.[/b]
## Splitting the whole block on the separator makes the first segment the markers
## and the preamble with the first entry glued to the end of it, and the preamble
## contains a ". " of its own — so entry one parsed as prose and was dropped, and
## every document reported one section short.
static func _listed(index: String) -> PackedStringArray:
	var out := PackedStringArray()
	for entry: String in _row(index).split("·"):
		var cleaned := entry.replace("**", "").strip_edges()
		var dot := cleaned.find(". ")
		if dot <= 0 or not cleaned.substr(0, dot).is_valid_int():
			continue
		out.append(cleaned)
	return out


## The rendered entry row of an index block: the last non-empty line before the
## closing marker. The generator writes the markers, the preamble, then the row.
static func _row(index: String) -> String:
	var lines := index.split("\n")
	for i: int in range(lines.size() - 1, -1, -1):
		var line := lines[i].strip_edges()
		if line.is_empty() or line == END:
			continue
		return line
	return ""


func _documents() -> PackedStringArray:
	var out := PackedStringArray()
	for name: String in DirAccess.get_files_at(DOCS_ROOT):
		if name.ends_with(".md"):
			out.append("%s/%s" % [DOCS_ROOT, name])
	out.sort()
	return out
