#!/usr/bin/env python3
"""Regenerates the section index at the top of each of the thirteen documents.

A document here runs to two thousand lines and a hundred headings, and the only
way to find §7.7 in it was to search for the string. That is fine for a machine
and useless for deciding *whether* a document has anything to say about a topic
before opening it — which is the question a session actually asks.

So each document carries a short index of its own top-level sections, between two
markers, immediately after its title. Top-level sections are the architecture's
chapters: they are numbered, they are stable, and they change roughly never, so
the index is cheap to keep true and does not churn on ordinary edits.

**It is generated rather than written, and checked rather than trusted.**
`LEARNED_FACTS.md` fact 64: a list that must be maintained by hand to stay honest
does not stay honest, and it rots in the direction of looking complete.
`tests/arch/test_doc_indexes.gd` fails the build when a document's index no longer
matches its headings, and this script is how you fix that:

    python3 tools/ci/doc_index.py            # rewrite every index
    python3 tools/ci/doc_index.py --check    # exit 1 if any is stale
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
DOCS = os.path.join(ROOT, "docs")

BEGIN = "<!-- SECTION INDEX -->"
END = "<!-- END SECTION INDEX -->"

# A top-level section: `## 7. Traction`. The number is required, which is what
# keeps prose headings and the GDScript `##` doc comments inside fenced code
# blocks out of the index.
HEADING = re.compile(r"^## (\d+)\.\s+(.*?)\s*$")

PREAMBLE = (
    "**Sections.** Generated by `tools/ci/doc_index.py` from the headings below "
    "and checked by `tests/arch/test_doc_indexes.gd`; edit the headings, not this "
    "list."
)


def sections(text):
    """Top-level numbered sections, as (number, title), skipping fenced blocks."""
    out = []
    fenced = False
    for line in text.split("\n"):
        if line.startswith("```"):
            fenced = not fenced
            continue
        if fenced:
            continue
        m = HEADING.match(line)
        if m is not None:
            out.append((m.group(1), m.group(2)))
    return out


def index_block(text):
    found = sections(text)
    if not found:
        return None
    rows = " · ".join("**%s.** %s" % (n, t) for n, t in found)
    return "%s\n\n%s\n\n%s\n%s" % (BEGIN, PREAMBLE, rows, END)


def rewrite(text):
    """The document with its index replaced, or inserted after the title."""
    block = index_block(text)
    if block is None:
        return text
    if BEGIN in text and END in text:
        head = text[: text.index(BEGIN)]
        tail = text[text.index(END) + len(END) :]
        return head + block + tail
    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.startswith("# "):
            return "\n".join(lines[: i + 1]) + "\n\n" + block + "\n" + "\n".join(lines[i + 1 :])
    return block + "\n\n" + text


def main(argv):
    check = "--check" in argv
    stale = []
    for name in sorted(os.listdir(DOCS)):
        if not name.endswith(".md"):
            continue
        path = os.path.join(DOCS, name)
        text = open(path).read()
        updated = rewrite(text)
        if updated == text:
            continue
        if check:
            stale.append(name)
        else:
            open(path, "w").write(updated)
            print("indexed %s" % name)
    if check and stale:
        print("stale section index in: %s" % ", ".join(stale), file=sys.stderr)
        print("run: python3 tools/ci/doc_index.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
