extends TestCase
## [ManifoldChecker] against the cases the engine's own behaviour was measured
## on, for [code]docs/PROCEDURAL_STRUCTURE_SLICING.md[/code] §3.1.
##
## [b]Every expectation here is what Godot 4.7.1's CSG actually did[/b], probed
## directly rather than reasoned about. That matters more than usual: the naive
## predicate — count edge uses by vertex index, demand exactly two — disagrees
## with the engine on two of the six cases below, and both disagreements are in
## the direction of refusing geometry that bakes perfectly well.
##
## The measured results, from the probe recorded in HANDOFF §3.58 and §3.59:
##
## [codeblock]
## BoxMesh (24 split verts, closed)   engine: bakes      naive index check: 24 boundary
## SphereMesh (UV seam, pole fans)    engine: bakes      naive index check: fails
## welded grid box                    engine: bakes      agrees
## cylinder with a TAU float seam     engine: DISCARDS   agrees
## open two-triangle sheet            engine: DISCARDS   agrees
## box with one face deleted          engine: DISCARDS   agrees
## [/codeblock]


func _array_mesh(primitive: Mesh) -> ArrayMesh:
	var m := ArrayMesh.new()
	m.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, primitive.surface_get_arrays(0))
	return m


## ===== THE CASES THE ENGINE ACCEPTS ====================================


## The case that rules out the naive predicate. A box is 8 corners and 24
## vertices; welding by position is what recovers the fact that it is closed.
func test_a_box_with_split_vertices_is_a_solid() -> void:
	var bm := BoxMesh.new()
	bm.size = Vector3(3, 3, 3)
	var report := ManifoldChecker.check_mesh(_array_mesh(bm))
	check_true(report.ok, "BoxMesh is a closed solid: %s" % report.summary())
	check_eq(report.boundary_edges, 0, "no holes")
	check_eq(report.excess_edges, 0, "no fins")
	# The weld is the whole mechanism, so assert that it happened rather than
	# only that the verdict came out right.
	check_eq(report.raw_vertex_count, 24, "a box arrives as 24 split vertices")
	check_eq(report.welded_vertex_count, 8, "and welds to its 8 corners")


## Degenerate triangles are reported and are not fatal. A sphere's pole fans are
## the standard case and the engine bakes them.
func test_a_sphere_with_pole_fans_is_a_solid() -> void:
	var sm := SphereMesh.new()
	sm.radius = 1.5
	sm.height = 3.0
	var report := ManifoldChecker.check_mesh(_array_mesh(sm))
	check_true(report.ok, "SphereMesh is a closed solid: %s" % report.summary())
	check_true(
		report.degenerate_triangles > 0,
		"and it does carry degenerate triangles (%d), which are not fatal"
			% report.degenerate_triangles
	)


func test_a_watertight_grid_box_is_a_solid() -> void:
	var report := ManifoldChecker.check_mesh(_grid_box(6, 4.0))
	check_true(report.ok, "a welded grid box is a closed solid: %s" % report.summary())
	check_eq(report.degenerate_triangles, 0, "and has no slivers")


## ===== THE CASES THE ENGINE SILENTLY DISCARDS ==========================


## The failure a DCC export actually produces, and the reason this gate exists:
## a seam whose two sides were generated by different arithmetic.
func test_a_float_seam_leaves_the_surface_open() -> void:
	var report := ManifoldChecker.check_mesh(_seam_cylinder(12, 24, 4.0, 10.0))
	check_false(report.ok, "a cylinder with a TAU float seam is not a solid")
	check_true(
		report.boundary_edges > 0,
		"and the seam shows up as boundary edges, got %d" % report.boundary_edges
	)
	check_true(
		report.summary().contains("discard"),
		"the message says what the engine will do about it: %s" % report.summary()
	)


func test_an_open_sheet_is_not_a_solid() -> void:
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = PackedVector3Array(
		[Vector3(-2, 0, -2), Vector3(2, 0, -2), Vector3(2, 0, 2), Vector3(-2, 0, 2)]
	)
	arrays[Mesh.ARRAY_INDEX] = PackedInt32Array([0, 1, 2, 0, 2, 3])
	var report := ManifoldChecker.check_arrays(arrays)
	check_false(report.ok, "a flat sheet is not a solid")
	check_eq(report.boundary_edges, 4, "its four sides are all boundary")


## The artist-forgot-to-close-it case. The engine bakes this to nothing at all,
## which is worse than baking it wrong.
func test_a_box_missing_one_face_is_not_a_solid() -> void:
	var bm := BoxMesh.new()
	bm.size = Vector3(2, 2, 2)
	var full: Array = bm.surface_get_arrays(0)
	var fi: PackedInt32Array = full[Mesh.ARRAY_INDEX]
	var holed := PackedInt32Array()
	for t: int in (fi.size() / 3) - 2:
		holed.append_array(PackedInt32Array([fi[t * 3], fi[t * 3 + 1], fi[t * 3 + 2]]))
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = full[Mesh.ARRAY_VERTEX]
	arrays[Mesh.ARRAY_INDEX] = holed
	var report := ManifoldChecker.check_arrays(arrays)
	check_false(report.ok, "a box missing a face is not a solid")
	check_eq(report.boundary_edges, 4, "the missing face leaves four boundary edges")


## A duplicated face is the other way a DCC export goes wrong — a mirror modifier
## applied twice — and it produces edges shared by four triangles rather than
## holes, so a boundary-only check would pass it.
func test_a_duplicated_face_is_not_a_solid() -> void:
	var bm := BoxMesh.new()
	bm.size = Vector3(2, 2, 2)
	var full: Array = bm.surface_get_arrays(0)
	var fi: PackedInt32Array = full[Mesh.ARRAY_INDEX]
	var doubled := fi.duplicate()
	doubled.append_array(PackedInt32Array([fi[0], fi[1], fi[2], fi[3], fi[4], fi[5]]))
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = full[Mesh.ARRAY_VERTEX]
	arrays[Mesh.ARRAY_INDEX] = doubled
	var report := ManifoldChecker.check_arrays(arrays)
	check_false(report.ok, "a box with one face duplicated is not a solid")
	check_true(
		report.excess_edges > 0,
		"and it is caught by excess edges rather than by holes, got %d" % report.excess_edges
	)
	check_eq(report.boundary_edges, 0, "a boundary-only check would have passed it")


## ===== THE GATE ========================================================


## The gate's accept path only. Its refuse path's whole extra behaviour is a
## [method @GlobalScope.push_error], and `tools/ci/run_all_checks.sh` fails the
## suite on any engine error printed during it (HANDOFF §3.34) — which is the
## correct behaviour for the wrapper and means a test must not deliberately
## provoke one. The refusals are asserted through [method
## ManifoldChecker.check_mesh] above, which is what `require` decides on.
func test_require_admits_a_solid() -> void:
	var bm := BoxMesh.new()
	bm.size = Vector3(1, 1, 1)
	check_true(ManifoldChecker.require(_array_mesh(bm), "a box"), "a solid is admitted")


## The two empty cases the gate has to refuse, asserted without provoking the
## error that reporting them prints.
func test_nothing_and_an_empty_mesh_are_not_solids() -> void:
	check_false(ManifoldChecker.check_mesh(null).ok, "a null mesh is not a solid")
	check_false(ManifoldChecker.check_mesh(ArrayMesh.new()).ok, "an empty mesh is not a solid")


## ===== FIXTURES ========================================================


## A cylinder whose seam is closed by arithmetic rather than by construction:
## cos(TAU) and cos(0) differ in the last bits, so the two sides never weld.
func _seam_cylinder(rings: int, seg: int, r: float, h: float) -> ArrayMesh:
	var st := SurfaceTool.new()
	st.begin(Mesh.PRIMITIVE_TRIANGLES)
	for y: int in rings:
		var y0 := -h * 0.5 + h * float(y) / float(rings)
		var y1 := -h * 0.5 + h * float(y + 1) / float(rings)
		for s: int in seg:
			var a0 := TAU * float(s) / float(seg)
			var a1 := TAU * float(s + 1) / float(seg)
			st.add_vertex(Vector3(cos(a0) * r, y0, sin(a0) * r))
			st.add_vertex(Vector3(cos(a0) * r, y1, sin(a0) * r))
			st.add_vertex(Vector3(cos(a1) * r, y1, sin(a1) * r))
			st.add_vertex(Vector3(cos(a0) * r, y0, sin(a0) * r))
			st.add_vertex(Vector3(cos(a1) * r, y1, sin(a1) * r))
			st.add_vertex(Vector3(cos(a1) * r, y0, sin(a1) * r))
	st.index()
	return st.commit()


## A subdivided box welded by quantised position at build time, so it is closed
## by construction rather than by luck.
func _grid_box(n: int, s: float) -> ArrayMesh:
	var verts := PackedVector3Array()
	var idx := PackedInt32Array()
	var seen: Dictionary = {}
	var put := func(p: Vector3) -> int:
		var k := Vector3i(roundi(p.x * 4096.0), roundi(p.y * 4096.0), roundi(p.z * 4096.0))
		if seen.has(k):
			return int(seen[k])
		var i := verts.size()
		verts.push_back(p)
		seen[k] = i
		return i
	for normal: Vector3 in [
		Vector3.RIGHT, Vector3.LEFT, Vector3.UP, Vector3.DOWN, Vector3.BACK, Vector3.FORWARD
	]:
		var u := Vector3(normal.y, normal.z, normal.x)
		var v := normal.cross(u)
		for a: int in n:
			for b: int in n:
				var c := normal * (s * 0.5)
				var fa0 := (-1.0 + 2.0 * float(a) / float(n)) * s * 0.5
				var fa1 := (-1.0 + 2.0 * float(a + 1) / float(n)) * s * 0.5
				var fb0 := (-1.0 + 2.0 * float(b) / float(n)) * s * 0.5
				var fb1 := (-1.0 + 2.0 * float(b + 1) / float(n)) * s * 0.5
				var i00 := put.call(c + u * fa0 + v * fb0) as int
				var i10 := put.call(c + u * fa1 + v * fb0) as int
				var i11 := put.call(c + u * fa1 + v * fb1) as int
				var i01 := put.call(c + u * fa0 + v * fb1) as int
				idx.append_array(PackedInt32Array([i00, i10, i11, i00, i11, i01]))
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_INDEX] = idx
	var m := ArrayMesh.new()
	m.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return m
